package com.karol.readingsapp.ui

import java.text.NumberFormat
import java.util.Locale

data class LocalizedStrings(
    val todaysReadings: String,
    val selectedReadings: String,
    val firstReading: String,
    val secondReading: String,
    val thirdReading: String,
    val nextReading: String,
    val noReadings: String,
    val noReadingsShort: String,
    val availableBibles: String,
    val home: String,
    val calendar: String,
    val bible: String,
    val settings: String,
    val about: String,
    val contact: String,
    val theTeam: String,
    val appTitle: String,
    val bibleTranslation: String,
    val saveConfig: String,
    val back: String,
    val reset: String,
    val sync: String,
    val parallelReading: String,
    val loadingReading: String,
    val previousMonth: String,
    val nextMonth: String,
    val selectBible: String,
    val book: String,
    val chapter: String,
    val verse: String,
    val developerNoteTitle: String,
    val developerNoteContent: String,
    val appDescription: String,
    val copyrightNotice: String,
    val developedBy: String,
    val appearance: String,
    val themeSkyBlue: String,
    val themePurple: String,
    val themeSepia: String,
    val themeDarkFrostedGlass: String,
    val downloadAll: String,
    val clearOfflineData: String,
    val retry: String,
    val downloading: String,
    val downloaded: String,
    val failed: String,
    val locale: Locale,
    val bookNames: Map<Int, String> = emptyMap(),
)

object Localization {
    private val EnglishBooks =
        mapOf(
            0 to "Genesis",
            1 to "Exodus",
            2 to "Leviticus",
            3 to "Numbers",
            4 to "Deuteronomy",
            5 to "Joshua",
            6 to "Judges",
            7 to "Ruth",
            8 to "1 Samuel",
            9 to "2 Samuel",
            10 to "1 Kings",
            11 to "2 Kings",
            12 to "1 Chronicles",
            13 to "2 Chronicles",
            14 to "Ezra",
            15 to "Nehemiah",
            16 to "Esther",
            17 to "Job",
            18 to "Psalms",
            19 to "Proverbs",
            20 to "Ecclesiastes",
            21 to "Song of Solomon",
            22 to "Isaiah",
            23 to "Jeremiah",
            24 to "Lamentations",
            25 to "Ezekiel",
            26 to "Daniel",
            27 to "Hosea",
            28 to "Joel",
            29 to "Amos",
            30 to "Obadiah",
            31 to "Jonah",
            32 to "Micah",
            33 to "Nahum",
            34 to "Habakkuk",
            35 to "Zephaniah",
            36 to "Haggai",
            37 to "Zechariah",
            38 to "Malachi",
            39 to "Matthew",
            40 to "Mark",
            41 to "Luke",
            42 to "John",
            43 to "Acts",
            44 to "Romans",
            45 to "1 Corinthians",
            46 to "2 Corinthians",
            47 to "Galatians",
            48 to "Ephesians",
            49 to "Philippians",
            50 to "Colossians",
            51 to "1 Thessalonians",
            52 to "2 Thessalonians",
            53 to "1 Timothy",
            54 to "2 Timothy",
            55 to "Titus",
            56 to "Philemon",
            57 to "Hebrews",
            58 to "James",
            59 to "1 Peter",
            60 to "2 Peter",
            61 to "1 John",
            62 to "2 John",
            63 to "3 John",
            64 to "Jude",
            65 to "Revelation",
        )

    private val HindiBooks =
        mapOf(
            0 to "उत्पत्ति",
            1 to "निर्गमन",
            2 to "लैव्यव्यवस्था",
            3 to "गिनती",
            4 to "व्यवस्थाविवरण",
            5 to "यहोशू",
            6 to "न्यायियों",
            7 to "रूत",
            8 to "1 शमूएल",
            9 to "2 शमूएल",
            10 to "1 राजा",
            11 to "2 राजा",
            12 to "1 इतिहास",
            13 to "2 इतिहास",
            14 to "एज्रा",
            15 to "नहेमायाह",
            16 to "एस्तेर",
            17 to "अय्यूब",
            18 to "भजन संहिता",
            19 to "नीतिवचन",
            20 to "सभोपदेशक",
            21 to "श्रेष्ठगीत",
            22 to "यशायाह",
            23 to "यिर्मयाह",
            24 to "विलापगीत",
            25 to "यहेजकेल",
            26 to "दानिय्येल",
            27 to "होशे",
            28 to "योएल",
            29 to "आमोस",
            30 to "ओबद्याह",
            31 to "योना",
            32 to "मीका",
            33 to "नहूम",
            34 to "हबक्कूक",
            35 to "सपन्याह",
            36 to "हाग्गै",
            37 to "जकर्याह",
            38 to "मलाकी",
            39 to "मत्ती",
            40 to "मरकुस",
            41 to "लूका",
            42 to "यूहन्ना",
            43 to "प्रेरितों के काम",
            44 to "रोमियों",
            45 to "1 कुरिन्थियों",
            46 to "2 कुरिन्थियों",
            47 to "गलातियों",
            48 to "इफिसियों",
            49 to "फिलिप्पियों",
            50 to "कुलुस्सियों",
            51 to "1 थिस्सलुनीकियों",
            52 to "2 थिस्सलुनीकियों",
            53 to "1 तीमुथियुस",
            54 to "2 तीमुथियुस",
            55 to "तीतुस",
            56 to "फिलेमोन",
            57 to "इब्रानियों",
            58 to "याकूब",
            59 to "1 पतरस",
            60 to "2 पतरस",
            61 to "1 यूहन्ना",
            62 to "2 यूहन्ना",
            63 to "3 यूहन्ना",
            64 to "यहूदा",
            65 to "प्रकाशितवाक्य",
        )

    private val BanglaBooks =
        mapOf(
            0 to "আদিপুস্তক",
            1 to "যাত্রাপুস্তক",
            2 to "লেবীয়পুস্তক",
            3 to "গণনাপুস্তক",
            4 to "দ্বিতীয় বিবরণ",
            5 to "যিহোশূয়",
            6 to "বিচারকর্তৃগণের বিবরণ",
            7 to "রুথ",
            8 to "১ শমূয়েল",
            9 to "২ শমূয়েল",
            10 to "১ রাজাবলি",
            11 to "২ রাজাবলি",
            12 to "১ বংশাবলি",
            13 to "২ বংশাবলি",
            14 to "এজরা",
            15 to "নেহেমিয়া",
            16 to "এস্থার",
            17 to "ইয়োব",
            18 to "গীতসংহিতা",
            19 to "হিতোপদেশ",
            20 to "উপদেশক",
            21 to "পরম গীত",
            22 to "যিশাইয়",
            23 to "যিরমিয়",
            24 to "বিলাপ",
            25 to "যিহিষ্কেল",
            26 to "দানিয়েল",
            27 to "হোশেয়",
            28 to "যোয়েল",
            29 to "আমোষ",
            30 to "ওবদিয়",
            31 to "যোনা",
            32 to "মীখা",
            33 to "নাহূম",
            34 to "হবক্কূক",
            35 to "সফনিয়",
            36 to "হগয়",
            37 to "সখরিয়",
            38 to "মালাখি",
            39 to "মথি",
            40 to "মার্ক",
            41 to "লূক",
            42 to "যোহন",
            43 to "প্রেরিত",
            44 to "রোমীয়",
            45 to "১ করিন্থীয়",
            46 to "২ করিন্থীয়",
            47 to "গালাতীয়",
            48 to "ইফিষীয়",
            49 to "ফিলিপীয়",
            50 to "কলসীয়",
            51 to "১ থিষলনীকীয়",
            52 to "২ থিষলনীকীয়",
            53 to "১ তীমথিয়",
            54 to "২ তীমথিয়",
            55 to "তীত",
            56 to "ফিলীমন",
            57 to "ইব্রীয়",
            58 to "যাকোব",
            59 to "১ পিতর",
            60 to "২ পিতর",
            61 to "১ যোহন",
            62 to "২ যোহন",
            63 to "৩ যোহন",
            64 to "যিহূদা",
            65 to "প্রকাশিত বাক্য",
        )

    private val KannadaBooks =
        mapOf(
            0 to "ಆದಿಕಾಂಡ",
            1 to "ವಿಮೋಚನಾಕಾಂಡ",
            2 to "ಯಾಜಕಕಾಂಡ",
            3 to "ಅರಣ್ಯಕಾಂಡ",
            4 to "ಧರ್ಮೋಪದೇಶಕಾಂಡ",
            5 to "ಯೆಹೋಶುವ",
            6 to "ನ್ಯಾಯಸ್ಥಾಪಕರು",
            7 to "ರೂತಳು",
            8 to "1 ಸಮುವೇಲನು",
            9 to "2 ಸಮುವೇಲನು",
            10 to "1 ಅರಸುಗಳು",
            11 to "2 ಅರಸುಗಳು",
            12 to "1 ಪೂರ್ವಕಾಲವೃತ್ತಾಂತ",
            13 to "2 ಪೂರ್ವಕಾಲವೃತ್ತಾಂತ",
            14 to "ಎಜ್ರನು",
            15 to "ನೆಹೆಮಿಯ",
            16 to "ಎಸ್ತೇರಳು",
            17 to "ಯೋಬನು",
            18 to "ಕೀರ್ತನೆಗಳು",
            19 to "ಜ್ಞಾನೋಕ್ತಿಗಳು",
            20 to "ಪ್ರಸಂಗಿ",
            21 to "ಪರಮ ಗೀತ",
            22 to "ಯೆಶಾಯ",
            23 to "ಯೆರೆಮಿಯ",
            24 to "ಪ್ರಲಾಪಗಳು",
            25 to "ಯೆಹೆಚ್ಚೇಲನು",
            26 to "ದಾನಿಯೇಲನು",
            27 to "ಹೋಶೇಯ",
            28 to "ಯೋವೇಲ",
            29 to "ಆಮೋಸ",
            30 to "ಓಬದ್ಯ",
            31 to "ಯೋನ",
            32 to "ಮೀಕ",
            33 to "ನಹೂಮ",
            34 to "ಹಬಕ್ಕೂಕ್ಕ",
            35 to "ಚೆಫನ್ಯ",
            36 to "ಹಗ್ಗಾಯ",
            37 to "ಜೆಕರ್ಯ",
            38 to "ಮಲಾಕಿ",
            39 to "ಮತ್ತಾಯನು",
            40 to "ಮಾರ್ಕನು",
            41 to "ಲೂಕನು",
            42 to "ಯೋಹಾನನು",
            43 to "ಅಪೊಸ್ತಲರ ಕೃತ್ಯಗಳು",
            44 to "ರೋಮಾಪುರದವರಿಗೆ",
            45 to "1 ಕೊರಿಂಥದವರಿಗೆ",
            46 to "2 ಕೊರಿಂಥದವರಿಗೆ",
            47 to "ಗಲಾತ್ಯದವರಿಗೆ",
            48 to "ಎಫೆಸದವರಿಗೆ",
            49 to "ಫಿಲಿಪ್ಪಿಯವರಿಗೆ",
            50 to "ಕೊಲೊಸ್ಸೆಯವರಿಗೆ",
            51 to "1 ಥೆಸಲೊನೀಕದವರಿಗೆ",
            52 to "2 ಥೆಸಲೊನೀಕದವರಿಗೆ",
            53 to "1 ತಿಮೊಥೆಯನಿಗೆ",
            54 to "2 ತಿಮೊಥೆಯನಿಗೆ",
            55 to "ತೀತನಿಗೆ",
            56 to "ಫಿಲೆಮೋನನಿಗೆ",
            57 to "ಇಬ್ರಿಯರಿಗೆ",
            58 to "ಯಾಕೋಬನು",
            59 to "1 ಪೇತ್ರನು",
            60 to "2 ಪೇತ್ರನು",
            61 to "1 ಯೋಹಾನನು",
            62 to "2 ಯೋಹಾನನು",
            63 to "3 ಯೋಹಾನನು",
            64 to "ಯೂದನು",
            65 to "ಪ್ರಕಟನೆ",
        )

    private val MalayalamBooks =
        mapOf(
            0 to "ഉല്പത്തി",
            1 to "പുറപ്പാട്",
            2 to "ലേവ്യപുസ്തകം",
            3 to "സംഖ്യാപുസ്തകം",
            4 to "ആവർത്തനം",
            5 to "യെഹോശുവ",
            6 to "ന്യായാധിപന്മാർ",
            7 to "രൂത്ത്",
            8 to "1 ശമുവേൽ",
            9 to "2 ശമുവേൽ",
            10 to "1 രാജാക്കന്മാർ",
            11 to "2 രാജാക്കന്മാർ",
            12 to "1 ദിനവൃത്താന്തം",
            13 to "2 ദിനവൃത്താന്തം",
            14 to "എസ്ര",
            15 to "നെഹെമ്യാവ്",
            16 to "എസ്തേർ",
            17 to "ഇയ്യോബ്",
            18 to "സങ്കീർത്തനങ്ങൾ",
            19 to "സദൃശവാക്യങ്ങൾ",
            20 to "സഭാപ്രസംഗി",
            21 to "ഉത്തമഗീതം",
            22 to "യെശയ്യാവ്",
            23 to "യിരെമ്യാവ്",
            24 to "വിലാപങ്ങൾ",
            25 to "യെഹെസ്കേൽ",
            26 to "ദാനീയേൽ",
            27 to "ഹോശേയ",
            28 to "യോവേൽ",
            29 to "ആമോസ്",
            30 to "ഓബദ്യാവ്",
            31 to "യോനാ",
            32 to "മീഖാ",
            33 to "നഹൂം",
            34 to "ഹബക്കൂക്",
            35 to "സെഫന്യാവ്",
            36 to "ഹഗ്ഗായി",
            37 to "സെഖര്യാവ്",
            38 to "മലാഖി",
            39 to "മത്തായി",
            40 to "മർക്കോസ്",
            41 to "ലൂക്കോസ്",
            42 to "യോഹന്നാൻ",
            43 to "പ്രവൃത്തികൾ",
            44 to "റോമർ",
            45 to "1 കൊരിന്ത്യർ",
            46 to "2 കൊരിന്ത്യർ",
            47 to "ഗലാത്യർ",
            48 to "എഫെസ്യർ",
            49 to "ഫിലിപ്പിയർ",
            50 to "കൊലോസ്യർ",
            51 to "1 തെസ്സലോനിക്യർ",
            52 to "2 തെസ്സലോനിക്യർ",
            53 to "1 തിമൊഥെയൊസ്",
            54 to "2 തിമൊഥെയൊസ്",
            55 to "തീത്തോസ്",
            56 to "ഫിലേമോൻ",
            57 to "എബ്രായർ",
            58 to "യാക്കോബ്",
            59 to "1 പത്രോസ്",
            60 to "2 പത്രോസ്",
            61 to "1 യോഹന്നാൻ",
            62 to "2 യോഹന്നാൻ",
            63 to "3 യോഹന്നാൻ",
            64 to "യൂദാ",
            65 to "വെളിപാട്",
        )

    private val TamilBooks =
        mapOf(
            0 to "ஆதியாகமம்",
            1 to "யாத்திராகமம்",
            2 to "லேவியராகமம்",
            3 to "எண்ணாகமம்",
            4 to "உபாகமம்",
            5 to "யோசுவா",
            6 to "நியாயாதிபதிகள்",
            7 to "ரூத்",
            8 to "1 சாமுவேல்",
            9 to "2 சாமுவேல்",
            10 to "1 இராஜாக்கள்",
            11 to "2 இராஜாக்கள்",
            12 to "1 நாளாகமம்",
            13 to "2 நாளாகமம்",
            14 to "எஸ்றா",
            15 to "நெகேமியா",
            16 to "எஸ்தர்",
            17 to "யோபு",
            18 to "சங்கீதம்",
            19 to "நீதிமொழிகள்",
            20 to "பிரசங்கி",
            21 to "உன்னதப்பாட்டு",
            22 to "ஏசாயா",
            23 to "எரேமியா",
            24 to "புலம்பல்",
            25 to "எசேக்கியேൽ",
            26 to "தானியேல்",
            27 to "ஓசியா",
            28 to "யோவேல்",
            29 to "ஆமோஸ்",
            30 to "ஒபதியா",
            31 to "யோனா",
            32 to "மீகா",
            33 to "நாகூம்",
            34 to "ஆபகூக்",
            35 to "செப்பனியா",
            36 to "ஆகாய்",
            37 to "சகரியா",
            38 to "மல்கியா",
            39 to "மத்தேயு",
            40 to "மாற்கு",
            41 to "லூக்கா",
            42 to "யோவான்",
            43 to "அப்போஸ்தலர் நடபடிகள்",
            44 to "ரோமர்",
            45 to "1 கொரிந்தியர்",
            46 to "2 கொரிந்தியர்",
            47 to "கலாத்தியர்",
            48 to "எபேசியர்",
            49 to "பிலிப்பியர்",
            50 to "கொலோசெயர்",
            51 to "1 தெசலோனிக்கேயர்",
            52 to "2 தெசலோனிக்கேயர்",
            53 to "1 தீமோத்தேயு",
            54 to "2 தீமோத்தேயு",
            55 to "தீத்து",
            56 to "பிலேமோன்",
            57 to "எபிரெயர்",
            58 to "யாக்கோபு",
            59 to "1 பேதுரு",
            60 to "2 பேதுரு",
            61 to "1 யோவான்",
            62 to "2 யோவான்",
            63 to "3 யோவான்",
            64 to "யூதா",
            65 to "வெளிப்படுத்தின விசேஷம்",
        )

    private val TeluguBooks =
        mapOf(
            0 to "ఆదికాండము",
            1 to "నిర్గమకాండము",
            2 to "లేవీయకాండము",
            3 to "సంఖ్యాకాండము",
            4 to "ద్వితీయోపదేశకాండము",
            5 to "యెహోషువ",
            6 to "న్యాయాధిపతులు",
            7 to "రూతు",
            8 to "1 సమూయేలు",
            9 to "2 సమూయేలు",
            10 to "1 రాజులు",
            11 to "2 రాజులు",
            12 to "1 దినవృత్తాంతములు",
            13 to "2 దినవృత్తాంతములు",
            14 to "ఎజ్రా",
            15 to "నెహెమ్యా",
            16 to "ఎస్తేరు",
            17 to "యోబు",
            18 to "కీర్తనల గ్రంథము",
            19 to "సామెతలు",
            20 to "ప్రసంగి",
            21 to "పరమగీతము",
            22 to "యెషయా",
            23 to "యిర్మీయా",
            24 to "విలాపవాక్యములు",
            25 to "యెహెజ్కేలు",
            26 to "దానియేలు",
            27 to "హోషేయ",
            28 to "యోవేలు",
            29 to "ఆమోసు",
            30 to "ఓబద్యా",
            31 to "యోనా",
            32 to "మీకా",
            33 to "నహూము",
            34 to "హబక్కూకు",
            35 to "జెఫన్యా",
            36 to "హగ్గయి",
            37 to "జెకర్యా",
            38 to "మలాకీ",
            39 to "మత్తయి",
            40 to "మార్కు",
            41 to "లూకా",
            42 to "యోహాను",
            43 to "అపొస్తలుల కార్యములు",
            44 to "రోమీయులకు",
            45 to "1 కొరింథీయులకు",
            46 to "2 కొరింథీయులకు",
            47 to "గలతీయులకు",
            48 to "ఎఫెసీయులకు",
            49 to "ఫిలిప్పీయులకు",
            50 to "కొలొస్సయులకు",
            51 to "1 థెస్సలొనీకయులకు",
            52 to "2 థెస్సలొనీకయులకు",
            53 to "1 తిమోతికి",
            54 to "2 తిమోతికి",
            55 to "తీతుకు",
            56 to "ఫిలేమోనుకు",
            57 to "హెబ్రీయులకు",
            58 to "యాకోబు",
            59 to "1 పేతురు",
            60 to "2 పేతురు",
            61 to "1 యోహాను",
            62 to "2 యోహాను",
            63 to "3 యోహాను",
            64 to "యూదా",
            65 to "ప్రకటన గ్రంథము",
        )

    private val English =
        LocalizedStrings(
            todaysReadings = "Today's Readings",
            selectedReadings = "Selected Readings",
            firstReading = "First Reading",
            secondReading = "Second Reading",
            thirdReading = "Third Reading",
            nextReading = "Next Reading",
            noReadings = "No readings scheduled for this section.",
            noReadingsShort = "No readings",
            availableBibles = "Available Bibles",
            home = "Home",
            calendar = "Calendar",
            bible = "Bible",
            settings = "Settings",
            about = "About",
            contact = "Contact",
            theTeam = "The Team",
            appTitle = "Daily Reading Companion",
            bibleTranslation = "Bible Translation",
            saveConfig = "Save Configuration",
            back = "Back",
            reset = "Reset",
            sync = "Sync Scroll",
            parallelReading = "Parallel Reading",
            loadingReading = "Loading content...",
            previousMonth = "Previous Month",
            nextMonth = "Next Month",
            selectBible = "Select Bible",
            book = "Book",
            chapter = "Chapter",
            verse = "Verse",
            developerNoteTitle = "Developer Note",
            developerNoteContent = "Our deepest gratitude to Our Almighty LORD for this opportunity to create something meaningful for the community.",
            appDescription = "A simple app to help you follow your daily Bible reading plan with multiple translations support.",
            copyrightNotice = "Bible translations included in this app are copyright of their respective publishers and copyright holders. All rights remain with their respective owners.",
            developedBy = "Developed by Karol",
            appearance = "Settings",
            themeSkyBlue = "Sky Blue",
            themePurple = "Purple",
            themeSepia = "Sepia",
            themeDarkFrostedGlass = "Dark Frosted Glass",
            downloadAll = "Download All Translations",
            clearOfflineData = "Clear Offline Data",
            retry = "Retry",
            downloading = "Downloading...",
            downloaded = "Downloaded",
            failed = "Failed",
            locale = Locale.US,
            bookNames = EnglishBooks,
        )

    private val Bangla =
        LocalizedStrings(
            todaysReadings = "আজকের পাঠ",
            selectedReadings = "নির্বাচিত পাঠ",
            firstReading = "প্রথম পাঠ",
            secondReading = "দ্বিতীয় পাঠ",
            thirdReading = "তৃতীয় পাঠ",
            nextReading = "পরবর্তী পাঠ",
            noReadings = "এই বিভাগের জন্য কোনো পাঠ নির্ধারিত নেই",
            noReadingsShort = "কোনো পাঠ নেই",
            availableBibles = "উপলব্ধ বাইবেল",
            home = "প্রচ্ছদ",
            calendar = "ক্যালেন্ডার",
            bible = "বাইবেল",
            settings = "সেটিংস",
            about = "সম্পর্কে",
            contact = "যোগাযোগ",
            theTeam = "দল",
            appTitle = "দৈনিক পাঠ সঙ্গী",
            bibleTranslation = "বাইবেল অনুবাদ",
            saveConfig = "সেভ করুন",
            back = "পিছনে",
            reset = "পুনরায় সেট করুন",
            sync = "স্ক্রোলিং সিঙ্ক করুন",
            parallelReading = "সমান্তরাল পাঠ",
            loadingReading = "লোড হচ্ছে...",
            previousMonth = "পূর্ববর্তী মাস",
            nextMonth = "পরবর্তী মাস",
            selectBible = "বাইবেল নির্বাচন করুন",
            book = "বই",
            chapter = "অধ্যায়",
            verse = "পদ",
            developerNoteTitle = "ডেভেলপার নোট",
            developerNoteContent = "সমাজের জন্য অর্থবহ কিছু তৈরি করার এই সুযোগ দেওয়ার জন্য আমরা সর্বশক্তিমান প্রভুর প্রতি আমাদের গভীর কৃতজ্ঞতা প্রকাশ করছি।",
            appDescription = "একাধিক অনুবাদ সমর্থন সহ আপনার প্রতিদিনের বাইবেল পড়ার পরিকল্পনা অনুসরণ করতে সহায়তা করার জন্য একটি সহজ অ্যাপ।",
            copyrightNotice = "Bible translations included in this app are copyright of their respective publishers and copyright holders. All rights remain with their respective owners.",
            developedBy = "Karol দ্বারা বিকশিত",
            appearance = "সেটিংস",
            themeSkyBlue = "আকাশী নীল",
            themePurple = "বেগুনী",
            themeSepia = "সেপিয়া",
            themeDarkFrostedGlass = "ডার্ক ফ্রস্টেড গ্লাস",
            downloadAll = "সব অনুবাদ ডাউনলোড করুন",
            clearOfflineData = "অফলাইন ডেটা মুছুন",
            retry = "আবার চেষ্টা করুন",
            downloading = "ডাউনলোড হচ্ছে...",
            downloaded = "ডাউনলোড করা হয়েছে",
            failed = "ব্যর্থ হয়েছে",
            locale = Locale.forLanguageTag("bn-BD"),
            bookNames = BanglaBooks,
        )

    private val Hindi =
        LocalizedStrings(
            todaysReadings = "आज के पाठ",
            selectedReadings = "चयनित पाठ",
            firstReading = "पहला पाठ",
            secondReading = "दूसरा पाठ",
            thirdReading = "तीसरा पाठ",
            nextReading = "अगला पाठ",
            noReadings = "इस अनुभाग के लिए कोई पाठ निर्धारित नहीं है",
            noReadingsShort = "कोई पाठ नहीं",
            availableBibles = "उपलब्ध बाइबिल",
            home = "मुख्य",
            calendar = "कैलेंडर",
            bible = "बाइबिल",
            settings = "सेटिंग्स",
            about = "के बारे में",
            contact = "संपर्क",
            theTeam = "हमारी टीम",
            appTitle = "दैनिक पाठ साथी",
            bibleTranslation = "बाइबिल अनुवाद",
            saveConfig = "सहेजें",
            back = "पीछे",
            reset = "रीसेट",
            sync = "स्क्रॉलिंग सिंक करें",
            parallelReading = "समानांतर पाठ",
            loadingReading = "सामग्री लोड हो रही है...",
            previousMonth = "पिछला महीना",
            nextMonth = "अगला महीना",
            selectBible = "बाइबिल चुनें",
            book = "पुस्तक",
            chapter = "अध्याय",
            verse = "पद",
            developerNoteTitle = "डेवलपर नोट",
            developerNoteContent = "समुदाय के लिए कुछ सार्थक बनाने का यह अवसर देने के लिए हम अपने सर्वशक्तिमान प्रभु के प्रति अत्यंत आभारी हैं।",
            appDescription = "एकाधिक अनुवादों के समर्थन के साथ आपकी दैनिक बाइबिल पढ़ने की योजना का पालन करने में आपकी सहायता करने के लिए एक सरल ऐप।",
            copyrightNotice = "Bible translations included in this app are copyright of their respective publishers and copyright holders. All rights remain with their respective owners.",
            developedBy = "Karol द्वारा विकसित",
            appearance = "सेटिंग्स",
            themeSkyBlue = "आसमान नीला",
            themePurple = "बैंगनी",
            themeSepia = "सेपिया",
            themeDarkFrostedGlass = "डार्क फ्रॉस्टेड ग्लास",
            downloadAll = "सभी अनुवाद डाउनलोड करें",
            clearOfflineData = "ऑफ़लाइन डेटा साफ़ करें",
            retry = "पुన: प्रयास करें",
            downloading = "डाउनलोड हो रहा है...",
            downloaded = "डाउनलोड किया गया",
            failed = "विफल",
            locale = Locale.forLanguageTag("hi-IN"),
            bookNames = HindiBooks,
        )

    private val Kannada =
        LocalizedStrings(
            todaysReadings = "ಇಂದಿನ ವಾಚನಗಳು",
            selectedReadings = "ಆಯ್ದ ಓದುಗಳು",
            firstReading = "ಮೊದಲನೆಯ ವಾಚನ",
            secondReading = "ಎರಡನೆಯ ವಾಚನ",
            thirdReading = "ಮೂರನೆಯ ವಾಚನ",
            nextReading = "ಮುಂದಿನ ಓದು",
            noReadings = "ಈ ವಿಭಾಗಕ್ಕೆ ಯಾವುದೇ ಓದುಗಳು ನಿಗದಿಯಾಗಿಲ್ಲ",
            noReadingsShort = "ಓದುಗಳಿಲ್ಲ",
            availableBibles = "ಲಭ್ಯವಿರುವ ಬೈಬಲ್‌ಗಳು",
            home = "ಮುಖಪುಟ",
            calendar = "ಕ್ಯಾಲೆಂಡರ್",
            bible = "ಬೈಬಲ್",
            settings = "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
            about = "ಬಗ್ಗೆ",
            contact = "ಸಂಪರ್ಕ",
            theTeam = "ನಮ್ಮ ತಂಡ",
            appTitle = "ದೈನಂದಿನ ಓದುವ ಒಡನಾಡಿ",
            bibleTranslation = "ಬೈಬಲ್ ಅನುವಾದ",
            saveConfig = "ಉಳಿಸಿ",
            back = "ಹಿಂದಕ್ಕೆ",
            reset = "ಮರುಹೊಂದಿಸಿ",
            sync = "ಸ್ಕ್ರೋಲಿಂಗ್ ಸಿಂಕ್ ಮಾಡಿ",
            parallelReading = "ಸಮಾಂತರ ಓದು",
            loadingReading = "ವಿಷಯ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
            previousMonth = "ಹಿಂದಿನ ತಿಂಗಳು",
            nextMonth = "ಮುಂದಿನ ತಿಂಗಳು",
            selectBible = "ಬೈಬಲ್ ಆಯ್ಕೆಮಾಡಿ",
            book = "ಪುಸ್ತಕ",
            chapter = "ಅಧ್ಯಾಯ",
            verse = "ವಚನ",
            developerNoteTitle = "ಡೆವಲಪರ್ ಟಿಪ್ಪಣಿ",
            developerNoteContent = "ಸಮುದಾಯಕ್ಕಾಗಿ ಅರ್ಥಪೂರ್ಣವಾದುದನ್ನು ಸೃಷ್ಟಿಸಲು ನಮಗೆ ಈ ಅವಕಾಶ ನೀಡಿದ ಆ ಸರ್ವಶಕ್ತ ದೇವರಿಗೆ ನಮ್ಮ ಅನಂತ ಕೃತಜ್ಞತೆಗಳು.",
            appDescription = "ಬಹು ಅನುವಾದಗಳ ಬೆಂಬలದೊಂದಿಗೆ ನಿಮ್ಮ ದೈನಂದಿನ ಬೈಬಲ್ ಓದುವ ಯೋಜನೆಯನ್ನು ಅನುಸರಿಸಲು ಸಹಾಯ ಮಾಡುವ ಸರಳ ಅಪ್ಲಿಕೇಶನ್.",
            copyrightNotice = "Bible translations included in this app are copyright of their respective publishers and copyright holders. All rights remain with their respective owners.",
            developedBy = "Karol ಅವರಿಂದ ಅಭಿವೃದ್ಧಿಪಡಿಸಲಾಗಿದೆ",
            appearance = "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
            themeSkyBlue = "ಆಕಾಶ ನೀಲಿ",
            themePurple = "ನೇರಳೆ",
            themeSepia = "ಸೆಪಿಯಾ",
            themeDarkFrostedGlass = "ಡಾರ್ಕ್ ಫ್ರಾಸ್ಟೆಡ್ ಗ್ಲಾಸ್",
            downloadAll = "ಎಲ್ಲಾ ಅನುವಾದಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
            clearOfflineData = "ಆಫ್‌ಲೈನ್ ಡೇಟಾ ಅಳಿಸಿ",
            retry = "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
            downloading = "ಡೌನ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
            downloaded = "ಡೌನ್‌ಲೋಡ್ ಆಗಿದೆ",
            failed = "ವಿಫಲವಾಗಿದೆ",
            locale = Locale.forLanguageTag("kn-IN"),
            bookNames = KannadaBooks,
        )

    private val Malayalam =
        LocalizedStrings(
            todaysReadings = "ഇന്നത്തെ വായനകൾ",
            selectedReadings = "തിരഞ്ഞെടുത്ത വായനകൾ",
            firstReading = "ഒന്നാം വായന",
            secondReading = "രണ്ടാം വായന",
            thirdReading = "മൂന്നാം വായന",
            nextReading = "അടുത്ത വായന",
            noReadings = "ഈ വിഭാഗത്തിനായി വായനകളൊന്നും നിശ്ചയിച്ചിട്ടില്ല",
            noReadingsShort = "വായനകളില്ല",
            availableBibles = "ലഭ്യമായ ബൈബിളുകൾ",
            home = "പ്രധാനം",
            calendar = "കലണ്ടർ",
            bible = "ബൈബിൾ",
            settings = "ക്രമീകരണങ്ങൾ",
            about = "കുറിച്ച്",
            contact = "ബന്ധപ്പെടുക",
            theTeam = "ഞങ്ങളുടെ ടീം",
            appTitle = "ദിനവായന സഹായി",
            bibleTranslation = "ബൈബിൾ വിവർത്തനം",
            saveConfig = "ക്രമീകരണം സംരക്ഷിക്കുക",
            back = "പുറകോട്ട്",
            reset = "പുനഃക്രമീകരിക്കുക",
            sync = "സ്ക്രോളിംഗ് സമന്വയിപ്പിക്കുക",
            parallelReading = "സമാന്തര വായന",
            loadingReading = "ഉള്ളടക്കം ലോഡ് ചെയ്യുന്നു...",
            previousMonth = "കഴിഞ്ഞ മാസം",
            nextMonth = "അടുത്ത മാസം",
            selectBible = "തിരഞ്ഞെടുക്കുക",
            book = "പുസ്തകം",
            chapter = "അദ്ധ്യായം",
            verse = "വാക്യം",
            developerNoteTitle = "ഡെവലപ്പർ കുറിപ്പ്",
            developerNoteContent = "സമൂഹത്തിനായി അർത്ഥവത്തായ ഒന്ന് സൃഷ്ടിക്കാൻ ഞങ്ങൾക്ക് ഈ അവസരം നൽകിയ സർവ്വശക്തനായ ദൈവത്തോട് ഞങ്ങൾ അങ്ങേയറ്റം കടപ്പെട്ടിരിക്കുന്നു.",
            appDescription = "ഒന്നിലധികം വിവർത്തനങ്ങളുടെ പിന്തുണയോടെ നിങ്ങളുടെ ദൈനംദിന ബൈബിൾ വായനാ പദ്ധതി പിന്തുടരാൻ സഹായിക്കുന്ന ലളിതമായ ആപ്പ്.",
            copyrightNotice = "Bible translations included in this app are copyright of their respective publishers and copyright holders. All rights remain with their respective owners.",
            developedBy = "Karol വികസിപ്പിച്ചത്",
            appearance = "ക്രമീകരണങ്ങൾ",
            themeSkyBlue = "സ്കൈ ബ്ലൂ",
            themePurple = "പർപ്പിൾ",
            themeSepia = "സെപ്പിയ",
            themeDarkFrostedGlass = "ഡാർക്ക് ഫ്രോസ്റ്റഡ് ഗ്ലാസ്",
            downloadAll = "എല്ലാ വിവർത്തനങ്ങളും ഡൗൺലോഡ് ചെയ്യുക",
            clearOfflineData = "ഓഫ്‌ലൈൻ ഡാറ്റ നീക്കം ചെയ്യുക",
            retry = "വീണ്ടും ശ്രമിക്കുക",
            downloading = "ഡൗൺലോഡ് ചെയ്യുന്നു...",
            downloaded = "ഡൗൺലോഡ് ചെയ്തു",
            failed = "പരാജയപ്പെട്ടു",
            locale = Locale.forLanguageTag("ml-IN"),
            bookNames = MalayalamBooks,
        )

    private val Tamil =
        LocalizedStrings(
            todaysReadings = "திருப்பலி வாசகங்கள்",
            selectedReadings = "தேர்ந்தெடுக்கப்பட்ட வாசிப்புகள்",
            firstReading = "முதல் வாசகம்",
            secondReading = "இரண்டாம் வாசகம்",
            thirdReading = "மூன்றாம் வாசகம்",
            nextReading = "அடுத்த வாசிப்பு",
            noReadings = "இந்தப் பகுதிக்கு வாசிப்புகள் எதுவும் திட்டமிடப்படவில்லை",
            noReadingsShort = "வாசிப்புகள் இல்லை",
            availableBibles = "கிடைக்கும் பைபிள்கள்",
            home = "முகப்பு",
            calendar = "நாட்காட்டி",
            bible = "வேதாகமம்",
            settings = "அமைப்புகள்",
            about = "பற்றி",
            contact = "தொடர்பு",
            theTeam = "எங்கள் குழு",
            appTitle = "தினசரி வாసిப்புத் துணை",
            bibleTranslation = "பைபிள் மொழிபெயர்ப்பு",
            saveConfig = "சேமி",
            back = "பின்செல்",
            reset = "மீட்டமை",
            sync = "ஸ்க்ரோலிங்கை ஒத்திசை",
            parallelReading = "இணையான வாசிப்பு",
            loadingReading = "உள்ளடக்கம் ஏற்றப்படுகிறது...",
            previousMonth = "முந்தைய மாதம்",
            nextMonth = "அடுத்த மாதம்",
            selectBible = "பைபிளைத் தேர்ந்தெடுக்கவும்",
            book = "புத்தகம்",
            chapter = "அதிகாரம்",
            verse = "வசனம்",
            developerNoteTitle = "டெவலப்பர் குறிப்பு",
            developerNoteContent = "சமுதாயத்திற்காக அர்த்தமுள்ள ஒன்றை உருவாக்குவதற்கான இந்த வாய்ப்பை வழங்கிய இறைவனுக்கு எங்களது மனமார்ந்த நன்றியைத் தெரிவித்துக் கொள்கிறோம்.",
            appDescription = "பல மொழிபெயர்ப்பு ஆதரவுடன் உங்களின் தினசரி பைபிள் வாசிப்புத் திட்டத்தைப் பின்பற்ற உதவும் எளிய செயலி.",
            copyrightNotice = "Bible translations included in this app are copyright of their respective publishers and copyright holders. All rights remain with their respective owners.",
            developedBy = "Karol உருவாக்கியது",
            appearance = "அமைப்புகள்",
            themeSkyBlue = "ஸ்கை ப்ளூ",
            themePurple = "ஊதா",
            themeSepia = "செபியா",
            themeDarkFrostedGlass = "டார்க் ஃப்ரோஸ்டட் கிளாஸ்",
            downloadAll = "அனைத்து மொழிபெயர்ப்புகளையும் பதிவிறக்கவும்",
            clearOfflineData = "ஆஃப்லைன் தரவை நீக்குக",
            retry = "மீண்டும் முயற்சி",
            downloading = "பதிவிறக்கம் செய்யப்படுகிறது...",
            downloaded = "பதிவிறக்கம் செய்யப்பட்டது",
            failed = "தோல்வியுற்றது",
            locale = Locale.forLanguageTag("ta-IN"),
            bookNames = TamilBooks,
        )

    private val Telugu =
        LocalizedStrings(
            todaysReadings = "ఈరోజు పఠనాలు",
            selectedReadings = "ఎంచుకున్న పఠనాలు",
            firstReading = "మొదటి పఠనము",
            secondReading = "రెండవ పఠనము",
            thirdReading = "మూడవ పఠనము",
            nextReading = "తదుపరి పఠనం",
            noReadings = "ఈ విభాగానికి ఎటువంటి పఠనాలు షెడ్యూల్ చేయబడలేదు",
            noReadingsShort = "పఠనాలు లేవు",
            availableBibles = "అందుబాటులో ఉన్న బైబిళ్లు",
            home = "మొదటి పేజీ",
            calendar = "క్యాలెండర్",
            bible = "బైబిల్",
            settings = "సెట్టింగ్‌లు",
            about = "గురించి",
            contact = "సంప్రదించండి",
            theTeam = "మా బృందం",
            appTitle = "రోజువారీ పఠన తోడు",
            bibleTranslation = "బైబిల్ అనువాదం",
            saveConfig = "సేవ్ చేయండి",
            back = "వెనుకకు",
            reset = "రీసెట్ చేయండి",
            sync = "స్క్రోలింగ్‌ను సింక్ చేయండి",
            parallelReading = "సమాంతర పఠనం",
            loadingReading = "కంటెంట్ లోడ్ అవుతోంది...",
            previousMonth = "గత నెల",
            nextMonth = "వచ్చే నెల",
            selectBible = "బైబిల్‌ను ఎంచుకోండి",
            book = "పుస్తకం",
            chapter = "అధ్యాయం",
            verse = "వచనము",
            developerNoteTitle = "డెవలపర్ గమనిక",
            developerNoteContent = "సమాజానికి అర్థవంతమైనదాన్ని సృష్టించే ఈ అవకాశాన్ని మాకు ప్రసాదించిన ఆ సర్వశక్తిమంతుడైన ప్రభువుకు మా హృదయపూర్వక కృతజ్ఞతలు.",
            appDescription = "బహుళ అనువాదాల మద్దతుతో మీ రోజువారీ బైబిల్ పఠన ప్రణాళికను అనుసరించడంలో మీకు సహాయపడే ఒక సాధారణ యాప్.",
            copyrightNotice = "Bible translations included in this app are copyright of their respective publishers and copyright holders. All rights remain with their respective owners.",
            developedBy = "Karol అభివృద్ధి చేశారు",
            appearance = "సెట్టింగ్‌లు",
            themeSkyBlue = "స్కై బ్లూ",
            themePurple = "పర్పుల్",
            themeSepia = "సెపియా",
            themeDarkFrostedGlass = "డార్క్ ఫ్రాస్టెడ్ గ్లాస్",
            downloadAll = "అన్ని అనువాదాలను డౌన్లోడ్ చేయండి",
            clearOfflineData = "ఆఫ్‌లైన్ డేటాను క్లియర్ చేయండి",
            retry = "మళ్లీ ప్రయత్నించండి",
            downloading = "డౌన్‌లోడ్ అవుతోంది...",
            downloaded = "డౌన్‌లోడ్ చేయబడింది",
            failed = "విఫలమైంది",
            locale = Locale.forLanguageTag("te-IN"),
            bookNames = TeluguBooks,
        )

    fun getStrings(language: String): LocalizedStrings {
        android.util.Log.d("Localization", "Requested language: '$language'")
        val lang = language.lowercase()
        val baseStrings =
            when {
                (lang.contains("bangla") || lang.contains("bengali") || (lang == "bn") || (lang == "ban")) -> Bangla
                (lang.contains("hindi") || (lang == "hi") || (lang == "hin")) -> Hindi
                (lang.contains("kannada") || (lang == "kn") || (lang == "kan")) -> Kannada
                (lang.contains("malayalam") || (lang == "ml") || (lang == "mal")) -> Malayalam
                (lang.contains("tamil") || (lang == "ta") || (lang == "tam")) -> Tamil
                (lang.contains("telugu") || (lang == "te") || (lang == "tel")) -> Telugu
                else -> English
            }

        // Ensure bookNames is never empty by falling back to English for missing entries
        return if (baseStrings.bookNames.size < 66) {
            val completeBookNames = EnglishBooks.toMutableMap()
            completeBookNames.putAll(baseStrings.bookNames)
            baseStrings.copy(bookNames = completeBookNames)
        } else {
            baseStrings
        }
    }

    fun localizeDigits(text: String, locale: Locale): String {
        val nf = NumberFormat.getIntegerInstance(locale)
        val zero = nf.format(0)
        if (zero == "0") return text
        val zeroChar = zero[0]
        val offset = zeroChar - '0'
        return text.map { char ->
            if (char in ('0'..'9')) (char + offset) else char
        }.joinToString("")
    }
}
